### PR TITLE
Revamped the theme

### PR DESCRIPTION
**Pull request by poltertec**

### CODE REVIEW

**Comment by ikeydoherty** [comment]
:o I kinda thought you'd disappeared forever, gotta be honest. Nice to see you back around :)

**Comment by poltertec** [comment]
Yeah srry new yob asks allot of my time :s

**Comment by ikeydoherty** [comment]
No harm no foul, just glad to see you're ok, that's the main thing. :)

**Comment by poltertec** [comment]
Thx :)
And :+1:  on the progress with Solus :)

**Comment by poltertec** [comment]
Btw Ikey, could you add me as collaborator for this repo.
Can't control issues, etc anymore atm :)

**Comment by ikeydoherty** [comment]
Oh yeah sorry

**Comment by ikeydoherty** [comment]
Done

**Comment by poltertec** [comment]
Thx :)

**Pull request merged**
