### PR TITLE
Add support to XFWM4

### PR DESCRIPTION
**Pull request by FabianOvrWrt**

### CODE REVIEW

**Comment by Limero** [comment]
This should be merged asap. It will make the theme work on Xfce too!

**Comment by ikeydoherty** [comment]
As can be seen there has been no activity from the maintainer in 2 months, and in truth we don't know what's happening.

Due to the inherent risk of this being abandoned (Apologies to the maintainer if this is not the case, but this is how it appears) it is *no longer the default artwork of Solus*

As such, at this point I am recommending a community fork.

**Comment by FabianOvrWrt** [comment]
Oh, how unfortunate. I hope somebody keeps this alive.

**Comment by poltertec** [comment]
Unable to merge this -> theme had a full rewrite.

**Pull request closed without merging**
